### ISSUE TITLE
update

### ISSUE THREAD

**Issue by DimonYoing** [fernanACM/NickUI#2]
Add the ability to change the nickname of another player

**Comment by fernanACM** [comment]
Ok

**Comment by DimonYoing** [comment]
And so that there are 2 buttons, 1 button is to change the player's nickname TEMPORARILY.
A 2 button to change FOREVER the nickname of the player

**Comment by DimonYoing** [comment]
And so that you can set the time for how long the player will walk under the changed nickname

**Comment by DimonYoing** [comment]
And, if possible, add a button so that the player's changed nickname does not work after exiting the game

**Comment by DimonYoing** [comment]
Ok, I'm waiting for the update, I really wanted to change my nickname to another
